name: Conventional Changelog Action
on: [pull_request]
jobs:
  changelog:
    runs-on: [ubuntu-latest]
    steps:
    - name: Edit changelog
      uses: TriPSs/conventional-changelog-action@v1.3.0
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        changelog-release-count: 5
