name: Codecov Report
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Generate coverage report
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
